ledger/urls.py
from django.urls import path
from .views import recipesInDatabase, getRecipe, homepage, addRecipe,addIngredient,addImage

urlpatterns = [
    path('home/', homepage, name='home'),
    path('recipes/list/', recipesInDatabase, name = 'recipebook'),
    path('recipe/<int:num>/', getRecipe, name='getRecipe'),
    path('recipe/add/', addRecipe, name='addRecipe'),
    path('recipe/add/ingredient', addIngredient, name='addIngredient'),
    path('recipe/<int:num>/add_image', addImage, name='addImage'),
]

app_name = 'ledger'

recipebook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ledger.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ledger/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Ingredient(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    class Meta:
        constraints = [models.UniqueConstraint(fields=['name'], name='uniqueIngredient')]

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    bio = models.CharField(max_length=255)

    def __str__(self):
        return self.user.username

class Recipe(models.Model):
    name = models.CharField(max_length=50)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    createdOn = models.DateTimeField(auto_now_add=True)
    updatedOn = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('ledger:getRecipe',args=[self.pk])
    
    class Meta:
        ordering = ['name']
        constraints = [models.UniqueConstraint(fields=['name','author'], name='uniqueNamePerAuthor')]


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.ingredient.name} - {self.quantity}'
    
    class Meta:
        constraints = [models.UniqueConstraint(fields=['recipe','ingredient'], name='uniqueIngredientPerRecipe')]

class RecipeImage(models.Model):
    image = models.ImageField(upload_to='images/',null=False)
    description = models.CharField(max_length=255)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('ledger:addImage',args=[self.recipe.pk])

    def __str__(self):
        return f'{self.recipe.name} image'

ledger/forms.py
from django import forms
from .models import Ingredient, Recipe, RecipeIngredient, RecipeImage

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name']

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['name']
    
class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredient
        fields = ['recipe','ingredient', 'quantity']

class RecipeImageForm(forms.ModelForm):
    class Meta:
        model = RecipeImage
        fields = ['image','description']

ledger/views.py
from django.shortcuts import render, redirect
from django.template import loader
from .models import Recipe, RecipeIngredient, RecipeImage, Profile
from .forms import RecipeForm, RecipeIngredientForm, IngredientForm, RecipeImageForm
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError

def homepage(request):
    return render(request,'homepage.html')

@login_required
def recipesInDatabase(request):
    items = Recipe.objects.all()
    return render(request, 'recipebook.html', {'recipes': items})

@login_required
def getRecipe(request,num):
    recipe = Recipe.objects.get(id=num)
    ingredients = RecipeIngredient.objects.filter(recipe=recipe)
    images = RecipeImage.objects.filter(recipe=recipe)
    return render(request, 'recipeNumber.html',{'recipe': recipe, 'ingredients': ingredients, 'images': images})

@login_required
def addRecipe(request):

    if request.method == 'POST':

        recipeForm = RecipeForm(request.POST)
        recipeIngredientForm = RecipeIngredientForm(request.POST)
        
        if recipeForm.is_valid(): 
            try:
                recipe = recipeForm.save(commit=False)
                profile = Profile.objects.get(user = request.user)
                recipeName = recipeForm.cleaned_data.get('name')

                if Recipe.objects.filter(name__iexact=recipeName, author=profile).exists():
                    recipeForm.add_error(None, 'Recipe already exists.')
                else:
                    recipe.name = recipeName
                    recipe.author = profile
                    recipe.save()
                    return redirect('ledger:addRecipe')
            
            except IntegrityError:
                recipeForm.add_error(None, 'Recipe Already Exists')


        if recipeIngredientForm.is_valid():
            try:
                recipeIngredient = recipeIngredientForm.save(commit=False)
                recipe = recipeIngredient.recipe

                recipeIngredient.save()
                recipe.save()
                return redirect('ledger:recipebook')
            except IntegrityError:
                recipeIngredientForm.add_error(None, 'Recipe Ingredient Already Exists')

    else:
        recipeForm = RecipeForm()
        recipeIngredientForm = RecipeIngredientForm()

    return render(request, 'addRecipe.html', {'recipe': recipeForm, 'recipeIngredient': recipeIngredientForm})

@login_required
def addIngredient(request):

    if request.method == 'POST':

        ingredientForm = IngredientForm(request.POST)
        if ingredientForm.is_valid():
            try:
                ingredientForm.save()
                return redirect('ledger:addRecipe')
            except IntegrityError:
                ingredientForm.add_error(None, 'Ingredient Already Exists')
    
    else:
        ingredientForm = IngredientForm()

    return render(request, 'addIngredient.html', {'ingredient': ingredientForm})

@login_required
def addImage(request,num):
    
    if request.method == 'POST':

        imageForm = RecipeImageForm(request.POST, request.FILES)
        if imageForm.is_valid():
            image = imageForm.save(commit=False)
            recipe = Recipe.objects.get(id=num)
            image.recipe = recipe
            image.save()
            recipe.save()
            return redirect('ledger:getRecipe', num)
    else:
        imageForm = RecipeImageForm()

    return render(request, 'addImage.html', {'image': imageForm})

ledger/templates/addImage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {{ block.super }}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ image.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

ledger/templates/addIngredient.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {{ block.super }}
    <form method="POST">
        {% csrf_token %}
        {{ ingredient.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

ledger/templates/addRecipe.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {{ block.super }}
    <h2>Recipe</h2>
    <form method="POST">
        {% csrf_token %}
        {{ recipe.as_p }}
        <button type="submit">Save</button>
    </form>
    
    <h2>RecipeIngredient</h2>
    <form method="POST">
        {% csrf_token %}
        {{ recipeIngredient.as_p }}
        <button type="submit">Save</button>
    </form>
    <a href="{% url 'ledger:addIngredient' %}" class="btn btn-primary">Add Ingredient</a>
{% endblock %}

ledger/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <title>{% block title %}Recipe Book {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark">
		<div class="container-fluid">
			<div>
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'ledger:recipebook' %}">Recipe Book</a>
					</li>
				</ul>
			</div>
			<div>
				<ul class="navbar-nav">
					<li class="nav-item">
						{% if user.is_authenticated %}
						    <form method="post" action="{% url 'logout' %}">
						        {% csrf_token %}
						        {{ form.as_p }}
						        <button class="nav-link" type="submit">Logout</button>
						    </form>
						{% else %}
						    <a href="{% url 'login' %}">Login</a>
						{% endif %}
					</li>
				</ul>
			</div>
		</div>
	</nav>
    <div id = "content">
        {% block content %} <h1>Recipe Book</h1> {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

ledger/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {{ block.super }}
    <ul>
        <h2>Log in to see recipes</h2>
    </ul>
{% endblock %}

ledger/templates/recipeNumber.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {{ block.super }}
    <ul>    
        <h2>Name: {{ recipe.name }}</h2>
        <h4>Author: {{ recipe.author }}</h4>
        <p>Created on: {{ recipe.createdOn }} | Last updated on: {{ recipe.updatedOn }} </p>
        <p>Ingredients:</p>
        {% for item in ingredients %}
            <li>{{ item.ingredient.name }} - {{ item.quantity }}</li>
        {% endfor %}

        <a href="{% url 'ledger:addImage' recipe.pk %}" class="btn btn-primary">Add Image</a>
        <h3>Images of {{ recipe.name }}:</h3>
        {% for item in images %}
            <img src="{{ item.image.url }}" alt="{{ item.description }}" style="max-width: 500px; max-height: 500px; width: auto; height: auto;">
            <p>{{ item.description }}</p>
        {% endfor %}
    </ul>
    <a href="{% url 'ledger:recipebook' %}" class="btn btn-primary">Back to Recipe List</a>
{% endblock %}

ledger/templates/recipebook.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {{ block.super }}
    <ul>
        <div class="d-flex justify-content-between align-items-center">
            <h2>Recipes</h2>
            <a href="{% url 'ledger:addRecipe' %}" class="btn btn-primary">Add Recipe</a>
        </div>
        {% for item in recipes %}
            <li><a href="{{ item.get_absolute_url }}">{{ item.name }}</a> by {{ item.author }}</li>
        {% endfor %}
    </ul>
{% endblock %}